version: "3.8"
services: 
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES} 
    depends_on:
      - api-postgres
    volumes:
      - ./:/app:ro
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  api-postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes: 
      - postgres-volume:/var/lib/posgresql

volumes:
  postgres-volume: {}
